### ISSUE TITLE
Can only add applications if you are using those specific DNS providers

### ISSUE THREAD

**Issue by drmarvin2k5** [morph1904/Tyger2#5] opened 2019-08-27 14:01 UTC
Hi Morph

I would like to add an application using a different DNS provider (DuckDNS).  I don't need anything to update the address.

**Comment by morph1904** [comment] 2019-08-27 14:13
Hi, 

Currently the DNS providers are there for an upcoming feature and are not currently used functionaly for the proxy. The list is a list of supported DNS providers for the new feature. Selecting any of the DNS providers from the list, even if your domain is not using that provider will not have any functional impact. 

Morph

**Comment by morph1904** [comment] 2019-08-28 07:32
Hi. 

A few things. Is this docker or ubuntu?
Can you try adding an address like example.example.com rather than example.example.example.com?

Have you looked at the logs or checked the response in devtools?

Morph

**Comment by drmarvin2k5** [comment] 2019-08-28 09:51
Hi there 

It’s a Docker container running on RancherOS. I installed it directly with command line (I also tried with Portainer). 

I’ve tried it with a shorter URL (3 components) and I’ve tried with and without HTTPS to no avail. Weird. 

Thoughts?

**Comment by drmarvin2k5** [comment] 2019-08-28 09:53
Sorry. Forgot about the Logs question. 

There doesn’t seem to be anything in the logs but “Checking for stale OCSP” and I’m not totally sure what you mean with the “dev tools” question. 

Cheers

Andrew

**Comment by morph1904** [comment] 2019-08-28 10:49
Hi. 

No probs we will get to the bottom of this. I am running this build as my live service without this issue on docker so I am just trying to narrow it down. 

So just to confirm the application address should be the full internal url so http://192.168.1.1:8000/appname for example. 

The external address should be something like: myapp.mydomain.com.

There are three main components at work. 

Caddy does the actual proxying and cert management. It reads the config generated by Tyger2 to know what to do with it. 

uWSGI this is a python observer essentially. It accepts the requests from the Tyger2 frontend which passes it to a django application to store and process, generating the Caddy config. 


Lastly there is the VUE Tyger2 frontend this processes your input and passes it to uWSGI for django to process via an api. 

The error you are getting is because django can not interpret the request to save your address correctly. 

If you use something like chrome dev tools ( hit f12) before trying to save your address and click on the network tab, you should see the request go to to the backend (a post request) and its response. If you can post the response here we can see why django is refusing to save your entry. 

Morph.

**Comment by drmarvin2k5** [comment] 2019-08-28 13:15
So it looks like the “response” is as follows. 

{"endpoints":["This field is required."]}

I wish I could offer more info.

**Comment by morph1904** [comment] 2019-08-28 15:15
That helps me. I am not in front of my computer at the moment. If you can give me a couple of hours I will take a look at what is happening and come back to you.

**Comment by drmarvin2k5** [comment] 2019-08-28 15:43
No worries. For some reason, Tyger1 craps out on me after a while for no obvious reason. So hopefully this is better. 

Cheers 

Andrew

**Comment by morph1904** [comment] 2019-08-28 16:43
Hi Andrew,

I have been able to replicate the issue. I am looking at a fix now I think I know the cause. 

How does TygerCaddy crap out on you? Does it just stop proxying requests or does the UI become unresponsive?

**Comment by morph1904** [comment] 2019-08-28 18:00
Sorry didnt mean to close the issue. I should have provided a fix to this and issue #6.

Please pull the latest version and give this a try, i have tested locally and updated my live build and all seems to be working.

**Comment by drmarvin2k5** [comment] 2019-08-28 18:27
It just stops proxying. Everything looks fine in the GUI. Recreating all the proxy’s doesn’t help. I just have to make a new container. 

Weird

**Comment by morph1904** [comment] 2019-08-28 18:44
That sounds like an issue with the Caddy process. 

Let me know when you have retried this issue and if solved I will close this ticket.

**Comment by drmarvin2k5** [comment] 2019-08-29 09:53
For now, I have Tyger2 working, which is great. Thanks for your help. 

Cheers

Andrew

**Comment by morph1904** [comment] 2019-08-29 09:59
No problem. Sorry for the bug!

**Closed by morph1904** 2019-08-29 09:59 UTC
Labels: bug, good first issue
