### ISSUE TITLE
Issue after installing - cant open web page at port 9091

### ISSUE THREAD

**Issue by derilium** [morph1904/Tyger2#28] opened 2020-07-30 13:35 UTC
I have followed the install procedure, ran the script and ran through the install (on the website) it then states to click the link including port 9091

When i click the link page cannot be displayed, i have also restarted the server to make sure that wasn't causing any problems

This is on ubuntu 18.04 server

Thanks

rob

**Comment by morph1904** [comment] 2020-07-31 08:21
Hi there. 
Have you opened the port on the firewall

Sudo ufw allow 9091

What are the service statuses of uwsgi and caddy?

**Comment by derilium** [comment] 2020-07-31 14:49
I actually installed it 3 times and was met with the same error, the
firewall wasn't on and when i looked into it more deeply caddy was never
installed any of the times, by looking through syslog it stated that
within /usr/lib/bin caddy file didnt exist.

By the sound of it the project could work really well for what i need, i
just couldn't get  it to work, this was on a vanilla Ubuntu 18.04 server,
static ip address etc

I've since wiped the VM but would be happy to try again.

I also looked into the caddy installation specifically (from multiple
websites) and the link they give to install it just doesnt work and has
been superseded.

Let me know if any of that does or doesnt make sense.

thanks

rob

**Comment by derilium** [comment] 2020-07-31 14:49
I actually installed it 3 times and was met with the same error, the firewall wasn't on and when i looked into it more deeply caddy was never installed any of the times, by looking through syslog it stated that within /usr/lib/bin caddy file didnt exist.

By the sound of it the project could work really well for what i need, i just couldn't get  it to work, this was on a vanilla Ubuntu 18.04 server, static ip address etc

I've since wiped the VM but would be happy to try again.

I also looked into the caddy installation specifically (from multiple websites) and the link they give to install it just doesnt work and has been superseded.

Let me know if any of that does or doesnt make sense.

thanks

rob

**Comment by morph1904** [comment] 2020-07-31 15:42
Thanks for the info BTW I have hidden your duplicate comment. 

I am currently working on the latest version which utilises caddy v2. This should solve the problem. 

In the meantime, it may be worth seeing if the docker version will work for you, it is easy to get running even if you house it on that ubuntu box. When I have the time later, I will look at modifying the install script to work with caddy 2 or at least fix caddy v1.

**Comment by derilium** [comment] 2020-07-31 16:41
That's great, I was going to give the docker a try this weekend and will
keep you posted.

Thanks

Rob

**Comment by JacobCoffee** [comment] 2020-08-07 16:37
I'm having the same issue - firewall is open.

I'll try the docker as well.

Can't wait for Caddy v2!

**Comment by khellendros74** [comment] 2020-09-04 14:44
same here nothing is LISTENING on port 9091
`
uwsgi    797        root    7u  IPv4  14375      0t0  TCP 127.0.0.1:45509 (LISTEN)
uwsgi    797        root    8u  IPv4  14378      0t0  TCP *:9090 (LISTEN)
uwsgi    903        root    7u  IPv4  14375      0t0  TCP 127.0.0.1:45509 (LISTEN)
uwsgi    904        root    7u  IPv4  14375      0t0  TCP 127.0.0.1:45509 (LISTEN)
uwsgi    905        root    7u  IPv4  14375      0t0  TCP 127.0.0.1:45509 (LISTEN)
uwsgi    906        root    7u  IPv4  14375      0t0  TCP 127.0.0.1:45509 (LISTEN)
uwsgi    907        root    7u  IPv4  14375      0t0  TCP 127.0.0.1:45509 (LISTEN)
uwsgi    908        root    8u  IPv4  14378      0t0  TCP *:9090 (LISTEN)
`

**Comment by morph1904** [comment] 2020-09-04 18:56
It looks like this issue is caused by caddy not being installed by the script anymore. The docker version builds it from source and so does not have this issue. 


I am not sure it is worth fixing for ubuntu as the majority of users are using docker, which is working fine, and I am close the RC of the latest version. I would be open to a pull request if someone would like a fix in the meantime.

**Comment by morph1904** [comment] 2020-09-12 20:49
Hi All, 

I am looking for some testers for the latest docker version if you are interested. Details on the readme.

**Comment by ksurl** [comment] 2020-10-01 00:02
I'm getting the same issue on docker. here's my compose file (version 2 for portainer):

```
version: "2"
services: 
  tyger2:
    image: morph1904/tyger2:beta
    container_name: tyger2
    volumes:
      - tyger2-data:/apps/Tyger2/data
      - tyger2-certs:/root/.caddy
    ports:
      - 443:443
      - 80:80
      - 9090:9090
      - 9091:9091
    restart: unless-stopped
```

after creating user at 9090/install, can't reach the 9091 admin page. the IP I used is the IP of my docker host, not the internal docker network IP of the container.

**Comment by morph1904** [comment] 2020-10-01 06:26
@ksurl please can you post the container logs and any more information you might have? When you say you are unable to reach the admin page, what error are you getting?

**Comment by ksurl** [comment] 2020-10-01 12:59
#### Log:
<details>
 <summary>(click to expand)</summary>

```
Starting ServicesActivating privacy features... 2020/09/30 23:58:21 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:58:21 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123127815,
2020/09/30 23:58:21 [INFO] [plex.bytesense.biz] acme: use tls-alpn-01 solver,
2020/09/30 23:58:21 [INFO] [plex.bytesense.biz] acme: Trying to solve TLS-ALPN-01,
*** has_emperor mode detected (fd: 5) ***,
[uWSGI] getting INI configuration from /apps/Tyger2/install/uwsgi.ini,
Wed Sep 30 23:58:22 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini has been spawned,
Wed Sep 30 23:58:22 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini is ready to accept requests,
2020/09/30 23:58:26 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123127815,
2020/09/30 23:58:27 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:58:28 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123127902,
2020/09/30 23:58:28 [INFO] [plex.bytesense.biz] acme: use tls-alpn-01 solver,
2020/09/30 23:58:28 [INFO] [plex.bytesense.biz] acme: Trying to solve TLS-ALPN-01,
2020/09/30 23:58:31 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123127902,
2020/09/30 23:58:32 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:58:32 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123127949,
2020/09/30 23:58:32 [INFO] [plex.bytesense.biz] acme: use tls-alpn-01 solver,
2020/09/30 23:58:32 [INFO] [plex.bytesense.biz] acme: Trying to solve TLS-ALPN-01,
2020/09/30 23:58:37 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123127949,
2020/09/30 23:58:38 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:58:38 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128017,
2020/09/30 23:58:38 [INFO] [plex.bytesense.biz] acme: Could not find solver for: tls-alpn-01,
2020/09/30 23:58:38 [INFO] [plex.bytesense.biz] acme: use http-01 solver,
2020/09/30 23:58:38 [INFO] [plex.bytesense.biz] acme: Trying to solve HTTP-01,
2020/09/30 23:58:45 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128017,
2020/09/30 23:58:46 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:58:47 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128095,
2020/09/30 23:58:47 [INFO] [plex.bytesense.biz] acme: Could not find solver for: tls-alpn-01,
2020/09/30 23:58:47 [INFO] [plex.bytesense.biz] acme: use http-01 solver,
2020/09/30 23:58:47 [INFO] [plex.bytesense.biz] acme: Trying to solve HTTP-01,
2020/09/30 23:58:50 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128095,
2020/09/30 23:58:51 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:58:51 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128134,
2020/09/30 23:58:51 [INFO] [plex.bytesense.biz] acme: Could not find solver for: tls-alpn-01,
2020/09/30 23:58:51 [INFO] [plex.bytesense.biz] acme: use http-01 solver,
2020/09/30 23:58:51 [INFO] [plex.bytesense.biz] acme: Trying to solve HTTP-01,
2020/09/30 23:58:56 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128134,
2020/09/30 23:58:57 failed to obtain certificate: acme: Error -> One or more domains had a problem:,
[plex.bytesense.biz] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from https://plex.bytesense.biz/.well-known/acme-challenge/5IPL3t8frwLl9bJDNAOpZbpoBAQUxRuC9N0ir7Apd2g [212.159.74.45]: 401, url: ,
Operations to perform:,
  Apply all migrations: addresses, admin, apps, auth, contenttypes, dns, endpoints, install, sessions,
Running migrations:,
  No migrations to apply.,
  Your models have changes that are not yet reflected in a migration, and so won't be applied.,
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.,
Looks installed, doing nothing,
uwsgi log exists, doing nothing,
uwsgi log exists, doing nothing,
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Sep 30 23:58:59 2020] ***,
compiled with version: 9.3.0 on 22 September 2020 12:49:07,
os: Linux-4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020,
nodename: f7c9a793070b,
machine: x86_64,
clock source: unix,
detected number of CPU cores: 3,
current working directory: /,
detected binary path: /usr/local/bin/uwsgi,
!!! no internal routing support, rebuild with pcre support !!!,
uWSGI running as root, you can use --uid/--gid/--chroot options,
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** ,
*** WARNING: you are running uWSGI without its master process manager ***,
your memory page size is 4096 bytes,
detected max file descriptor number: 1048576,
*** starting uWSGI Emperor ***,
Starting ServicesActivating privacy features... 2020/09/30 23:58:59 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:58:59 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128188,
2020/09/30 23:58:59 [INFO] [plex.bytesense.biz] acme: Could not find solver for: tls-alpn-01,
2020/09/30 23:58:59 [INFO] [plex.bytesense.biz] acme: use http-01 solver,
2020/09/30 23:58:59 [INFO] [plex.bytesense.biz] acme: Trying to solve HTTP-01,
*** has_emperor mode detected (fd: 5) ***,
[uWSGI] getting INI configuration from /apps/Tyger2/install/uwsgi.ini,
Wed Sep 30 23:59:00 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini has been spawned,
Wed Sep 30 23:59:00 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini is ready to accept requests,
2020/09/30 23:59:05 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128188,
2020/09/30 23:59:06 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:59:06 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128256,
2020/09/30 23:59:06 [INFO] [plex.bytesense.biz] acme: Could not find solver for: tls-alpn-01,
2020/09/30 23:59:06 [INFO] [plex.bytesense.biz] acme: use http-01 solver,
2020/09/30 23:59:06 [INFO] [plex.bytesense.biz] acme: Trying to solve HTTP-01,
2020/09/30 23:59:13 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128256,
2020/09/30 23:59:14 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:59:14 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128319,
2020/09/30 23:59:14 [INFO] [plex.bytesense.biz] acme: Could not find solver for: tls-alpn-01,
2020/09/30 23:59:14 [INFO] [plex.bytesense.biz] acme: use http-01 solver,
2020/09/30 23:59:14 [INFO] [plex.bytesense.biz] acme: Trying to solve HTTP-01,
2020/09/30 23:59:21 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128319,
2020/09/30 23:59:22 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:59:22 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128408,
2020/09/30 23:59:22 [INFO] [plex.bytesense.biz] acme: use tls-alpn-01 solver,
2020/09/30 23:59:22 [INFO] [plex.bytesense.biz] acme: Trying to solve TLS-ALPN-01,
2020/09/30 23:59:26 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128408,
2020/09/30 23:59:27 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:59:27 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128456,
2020/09/30 23:59:27 [INFO] [plex.bytesense.biz] acme: use tls-alpn-01 solver,
2020/09/30 23:59:27 [INFO] [plex.bytesense.biz] acme: Trying to solve TLS-ALPN-01,
2020/09/30 23:59:34 [INFO] Unable to deactivated authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128456,
2020/09/30 23:59:35 [INFO] [plex.bytesense.biz] acme: Obtaining bundled SAN certificate,
2020/09/30 23:59:36 [INFO] [plex.bytesense.biz] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/123128533,
2020/09/30 23:59:36 [INFO] [plex.bytesense.biz] acme: use tls-alpn-01 solver,
2020/09/30 23:59:36 [INFO] [plex.bytesense.biz] acme: Trying to solve TLS-ALPN-01,```
</details>

**Comment by morph1904** [comment] 2020-10-01 14:01
@ksurl I see the issue. A testing version of the Caddyfile.conf was included in the repo and this was causing issues as the domain does not terminate at your IP. I have updated this and I am waiting for the build to complete. 

Please can you remove your Container, and clear your data folder/volume, it may also be worth clearing your cached images of any reference to Tyger 2 and recreate your container pulling the latest image. This is essentially a clean install, and you should get the clean caddyfile.

**Comment by ksurl** [comment] 2020-10-01 14:02
Thanks. I'll check docker hub for the latest build timestamp before doing a new pull and redeploy from scratch

**Comment by morph1904** [comment] 2020-10-01 14:03
The build has now completed

**Comment by ksurl** [comment] 2020-10-01 14:13
this IP should be the private IP right? not public? if my subnet is 192.168.1.0/24 and my host is 192.168.1.10 it should be what is used in the 192.168.1.10:9090/install setup?

**Comment by morph1904** [comment] 2020-10-01 14:15
Yes, Both the frontend and backend services run in the same container. 9090 is the backend, 9091 is the frontend.

**Comment by ksurl** [comment] 2020-10-01 14:22
still can't access it. 

#### Log:
<details>
 <summary>(click to expand)</summary>

```
Assuming new install,
Looks installed, doing nothing,
uwsgi log exists, doing nothing,
uwsgi log exists, doing nothing,
*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Oct  1 14:10:58 2020] ***,
compiled with version: 9.3.0 on 01 October 2020 13:57:47,
os: Linux-4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020,
nodename: 814c81b76cc2,
machine: x86_64,
clock source: unix,
detected number of CPU cores: 3,
current working directory: /,
detected binary path: /usr/local/bin/uwsgi,
!!! no internal routing support, rebuild with pcre support !!!,
uWSGI running as root, you can use --uid/--gid/--chroot options,
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** ,
*** WARNING: you are running uWSGI without its master process manager ***,
your memory page size is 4096 bytes,
detected max file descriptor number: 1048576,
*** starting uWSGI Emperor ***,
*** has_emperor mode detected (fd: 5) ***,
[uWSGI] getting INI configuration from /apps/Tyger2/install/uwsgi.ini,
Thu Oct  1 14:10:59 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini has been spawned,
Thu Oct  1 14:10:59 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini is ready to accept requests,
Thu Oct  1 14:11:54 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini is now loyal,
Thu Oct  1 14:11:57 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini is now loyal,
Thu Oct  1 14:11:58 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini is now loyal,
```
</details>

**Comment by morph1904** [comment] 2020-10-01 15:33
OK. 

I have just pulled a new version of Tyger2 onto my dev docker host. I use portainer, here is my setup:
![image](https://user-images.githubusercontent.com/3823307/94828346-468c2480-0401-11eb-9b77-222e07c23d12.png)

Here is the volume configuration:
![image](https://user-images.githubusercontent.com/3823307/94829246-3a549700-0402-11eb-8946-33a9cdd5b1da.png)

My log looks the same as yours (except it does not show creating the log files, are you sure you deleted your volumes? Have you tried a path bind like mine?):

<details>
 <summary>(click to expand)</summary>

```
Assuming new install


Looks installed, doing nothing


Creating uwsgi.log


Creating uwsgi-access.log


*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Oct  1 15:20:19 2020] ***


compiled with version: 9.3.0 on 01 October 2020 13:57:47


os: Linux-5.8.0-20-generic #21-Ubuntu SMP Wed Sep 23 00:39:43 UTC 2020


nodename: 3caa4cef708b


machine: x86_64


clock source: unix


detected number of CPU cores: 4


current working directory: /


detected binary path: /usr/local/bin/uwsgi


!!! no internal routing support, rebuild with pcre support !!!


uWSGI running as root, you can use --uid/--gid/--chroot options


*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 


*** WARNING: you are running uWSGI without its master process manager ***


your memory page size is 4096 bytes


detected max file descriptor number: 1048576


*** starting uWSGI Emperor ***


Starting ServicesActivating privacy features... done.




Serving HTTP on port 9091 


http://:9091/api


http://:9091




*** has_emperor mode detected (fd: 5) ***


[uWSGI] getting INI configuration from /apps/Tyger2/install/uwsgi.ini


Thu Oct  1 15:20:20 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini has been spawned


Thu Oct  1 15:20:20 2020 - [emperor] vassal /apps/Tyger2/install/uwsgi.ini is ready to accept requests
```
</details>

This is my install screen (note how I have filled it out and the URL):
![image](https://user-images.githubusercontent.com/3823307/94829723-b8b13900-0402-11eb-99b4-043404b67646.png)

This was successful:
![image](https://user-images.githubusercontent.com/3823307/94829769-c6ff5500-0402-11eb-9167-beefdcdb247c.png)

Clicking the link on the success page then brings me to the login:
![image](https://user-images.githubusercontent.com/3823307/94829955-f615c680-0402-11eb-88c4-da4e866ce3d5.png)

Once logged in I see the main app:
![image](https://user-images.githubusercontent.com/3823307/94830057-12196800-0403-11eb-9d40-3eecb0230995.png)

My logs are unchanged at this point (correctly so). 

Also, these are the permissions set on my paths:
![image](https://user-images.githubusercontent.com/3823307/94830208-41c87000-0403-11eb-9065-f4605087aebf.png)

Is there any more information that you can provide that would help me assist you? What issue are you getting accessing the http://<YOUR IP HERE>:9091 address? What error are you receiving?

**Comment by ksurl** [comment] 2020-10-01 15:40
same permissions, owned by root, readable by group/other. browser error is site can't be reached, server refused to connect. using `nc` to check port opening, it is not listening on 9091, only 9090. let me try creating the container manually in portainer instead of using a stack. though it shouldn't make a difference.

**Comment by morph1904** [comment] 2020-10-01 15:50
I think it was still using the data from your volume with the duff caddyfile. Once the file is created Tyger tries to re-use it. If it is missing it generates a new one. 

Caddy actually serves the frontend in this version of TygerCaddy (a design flaw on my part that is rectified in the new version) so if the caddyfile is rubbish, the frontend becomes unavailble as Caddy is not working correctly and so can not serve the frontend.

**Comment by derilium** [comment] 2020-12-01 17:03
Did you get this working on a default install on ubuntu 18, i ran through
the process, configured through the web portal but then cant access it by
port 9091 - unable to connect

**Comment by morph1904** [comment] 2020-12-01 17:25
Hi @derilium, 

The Ubuntu installer script is not installing Caddy correctly on this version of TygerCaddy and as I am very close to releasing a completely new version based on the updated Caddy 2 platform, there is little point in fixing this issue as the majority of users are using docker. 

I would recommend either installing docker on your ubuntu server, and following the docker install steps (this should be very straightforward and the screenshots above should help). Or, you could assist with the testing of the latest version of TygerCaddy (also docker based) which does away with Python, uWSGI, and Caddy V1 altogether and is so far reportedly very stable with the current testers.

**Comment by morph1904** [comment] 2020-12-13 16:42
Closing Issue. 

Pull request is welcome, however not looking to fix this currently. The latest version will be docker first and has been very successful during testing.

**Closed by morph1904** 2020-12-13 16:42 UTC
